import { StyleSheet, Platform } from 'react-native';
import { theme } from '../../styles/theme';

export default StyleSheet.create({
  backgroundImage: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)', // Dark overlay for text contrast
  },
  container: {
    flex: 1,
  },
  mainWrapper: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  formScrollContent: {
    flexGrow: 1,
    width: '100%',
    maxWidth: 520,
    paddingHorizontal: 24,
    paddingTop: Platform.OS === 'ios' ? 20 : 40,
    paddingBottom: 40,
    alignSelf: 'center',
  },
  logoContainer: {
    alignItems: 'flex-start',
  },
  logoImage: {
    width: undefined,
    height: '50%',
    aspectRatio: 4.167,
  },
  sloganText: {
    color: '#ffffff',
    fontSize: 26,
    fontFamily: theme.fontFamily.bold,
    lineHeight: 34,
    marginBottom: 24,
    paddingLeft: 4,
  },
  card: {
    backgroundColor: 'rgba(20, 26, 21, 0.72)', // Translucent dark green/black
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    padding: 24,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 5,
  },
  cardTitle: {
    color: '#ffffff',
    fontSize: 24,
    fontFamily: theme.fontFamily.bold,
    marginBottom: 6,
  },
  cardSubtitle: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 14,
    fontFamily: theme.fontFamily.regular,
    lineHeight: 20,
    marginBottom: 24,
  },
  formContainer: {
    width: '100%',
  },
  inputGroup: {
    marginBottom: 20,
    position: 'relative',
  },
  inputLabel: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: 11,
    fontFamily: theme.fontFamily.semiBold,
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  rowInputs: {
    flexDirection: 'row',
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 52,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 12,
    paddingHorizontal: 16,
  },
  inputIcon: {
    marginRight: 12,
  },
  inputText: {
    flex: 1,
    color: '#ffffff',
    fontSize: 15,
    fontFamily: theme.fontFamily.regular,
    height: '100%',
  },
  dropdownSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 52,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 12,
    paddingHorizontal: 16,
  },
  dropdownValueText: {
    color: '#ffffff',
    fontSize: 15,
    fontFamily: theme.fontFamily.regular,
  },
  dropdownMenu: {
    position: 'absolute',
    top: 80,
    left: 0,
    right: 0,
    backgroundColor: '#1c241d', // Tinted dark green matching theme
    borderColor: 'rgba(255, 255, 255, 0.15)',
    borderWidth: 1,
    borderRadius: 12,
    overflow: 'hidden',
    zIndex: 9999,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 10,
  },
  dropdownOption: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
  },
  dropdownOptionText: {
    color: '#ffffff',
    fontSize: 15,
    fontFamily: theme.fontFamily.regular,
  },
  phoneInputWrapper: {
    flexDirection: 'row',
    height: 52,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 12,
    overflow: 'hidden',
  },
  countryCodeSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    borderRightWidth: 1,
    borderRightColor: 'rgba(255, 255, 255, 0.12)',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
  },
  flagText: {
    fontSize: 16,
    marginRight: 4,
  },
  countryCodeText: {
    color: '#ffffff',
    fontSize: 14,
    fontFamily: theme.fontFamily.medium,
  },
  phoneInput: {
    flex: 1,
    color: '#ffffff',
    paddingHorizontal: 16,
    fontSize: 15,
    fontFamily: theme.fontFamily.regular,
  },
  passwordInputWrapper: {
    position: 'relative',
    justifyContent: 'center',
  },
  eyeIconWrapper: {
    position: 'absolute',
    right: 16,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  submitButton: {
    backgroundColor: '#3b7a3e', // Premium Forest Green matching screenshot
    borderRadius: 12,
    height: 52,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 16,
    shadowColor: '#3b7a3e',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 4,
  },
  submitButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontFamily: theme.fontFamily.bold,
  },
  buttonArrow: {
    marginLeft: 8,
  },
  formFooter: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 24,
  },
  footerText: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 14,
    fontFamily: theme.fontFamily.regular,
  },
  footerLink: {
    color: '#ffffff',
    fontSize: 14,
    fontFamily: theme.fontFamily.bold,
  },
});
