import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#111214',
  },
  mainWrapper: {
    flex: 1,
  },
  rowDirection: {
    flexDirection: 'row',
  },
  columnDirection: {
    flexDirection: 'column',
  },
  leftSide: {
    backgroundColor: '#111214',
    paddingHorizontal: 24,
  },
  formScrollContent: {
    flexGrow: 1,
    maxWidth: 520,
    alignSelf: 'center',
    width: '100%',
    paddingVertical: 32,
  },
  desktopHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 60,
    marginTop: 20,
  },
  mobileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 40,
  },
  smallLogoBox: {
    backgroundColor: '#d9ab55',
    width: 28,
    height: 28,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    transform: [{ rotate: '-4deg' }],
  },
  smallLogoText: {
    color: '#111214',
    fontWeight: 'bold',
    fontSize: 16,
  },
  desktopHeaderBrand: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  mobileHeaderBrand: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  welcomeSection: {
    marginBottom: 36,
  },
  welcomeTitle: {
    color: '#ffffff',
    fontSize: 32,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  welcomeSubtitle: {
    color: '#8e929a',
    fontSize: 15,
    lineHeight: 22,
  },
  formContainer: {
    width: '100%',
  },
  inputGroup: {
    marginBottom: 24,
  },
  inputLabel: {
    color: '#8e929a',
    fontSize: 11,
    fontWeight: 'bold',
    letterSpacing: 1,
    marginBottom: 8,
  },
  passwordLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  forgotPasswordLink: {
    color: '#8e929a',
    fontSize: 11,
    textDecorationLine: 'none',
  },
  textInput: {
    backgroundColor: '#18191c',
    borderWidth: 1,
    borderColor: '#26282d',
    borderRadius: 8,
    color: '#ffffff',
    paddingVertical: 12,
    paddingHorizontal: 16,
    fontSize: 15,
    height: 48,
  },
  passwordInputWrapper: {
    position: 'relative',
    justifyContent: 'center',
  },
  eyeIconWrapper: {
    position: 'absolute',
    right: 16,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  submitButton: {
    backgroundColor: '#d9ab55',
    borderRadius: 8,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 12,
    shadowColor: '#d9ab55',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 4,
  },
  submitButtonText: {
    color: '#111214',
    fontSize: 16,
    fontWeight: 'bold',
  },
  formFooter: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 28,
  },
  footerText: {
    color: '#8e929a',
    fontSize: 14,
  },
  footerLink: {
    color: '#d9ab55',
    fontSize: 14,
    fontWeight: 'bold',
  },
  rightSide: {
    flex: 55,
    backgroundColor: '#16171a',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 48,
    borderLeftWidth: 1,
    borderLeftColor: '#202227',
  },
  brandShowcaseContent: {
    alignItems: 'center',
    maxWidth: 450,
  },
  tiltedCard: {
    backgroundColor: '#d9ab55',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 28,
    shadowColor: '#d9ab55',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 15,
    elevation: 8,
  },
  tiltedCardText: {
    color: '#111214',
    fontWeight: 'bold',
  },
  showcaseTitle: {
    color: '#ffffff',
    fontSize: 32,
    fontWeight: 'bold',
    marginTop: 16,
    marginBottom: 16,
    letterSpacing: 0.5,
    textAlign: 'center',
  },
  showcaseSubtitle: {
    color: '#a0a5ad',
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
  },
  mobileVisualFooter: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 32,
    backgroundColor: '#141517',
    borderTopWidth: 1,
    borderTopColor: '#202227',
  },
  mobileSlogan: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: 'bold',
    marginTop: 10,
    letterSpacing: 1,
  },
});
